import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        {
            name: 'Combo2',
            description: 'Value combo pack with 2 educational toys perfect for early learning and development',
            price: 599,
            salePrice: 499,
            saveAmount: 100,
            images: JSON.stringify(['https://example.com/combo2-1.jpg', 'https://example.com/combo2-2.jpg']),
            categoryId: 7,
            ageRange: '1-3 Years',
            stockQuantity: 35,
            vendor: 'Kuviyal',
            isCombo: true,
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            name: 'Combo4',
            description: 'Premium combo with 4 learning toys designed to enhance cognitive skills and motor development',
            price: 1199,
            salePrice: 999,
            saveAmount: 200,
            images: JSON.stringify(['https://example.com/combo4-1.jpg', 'https://example.com/combo4-2.jpg']),
            categoryId: 7,
            ageRange: '2-4 Years',
            stockQuantity: 28,
            vendor: 'Kuviyal',
            isCombo: true,
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            name: 'Budget Friendly 7 Toys Combo',
            description: 'Budget-friendly pack of 7 toys offering excellent value with variety of educational activities',
            price: 1799,
            salePrice: 1499,
            saveAmount: 300,
            images: JSON.stringify(['https://example.com/combo7-1.jpg', 'https://example.com/combo7-2.jpg', 'https://example.com/combo7-3.jpg']),
            categoryId: 7,
            ageRange: '1-4 Years',
            stockQuantity: 22,
            vendor: 'Kuviyal',
            isCombo: true,
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: '8 Toys Combo',
            description: 'Complete set of 8 developmental toys covering multiple learning areas for comprehensive growth',
            price: 1999,
            salePrice: 1699,
            saveAmount: 300,
            images: JSON.stringify(['https://example.com/combo8-1.jpg', 'https://example.com/combo8-2.jpg']),
            categoryId: 7,
            ageRange: '2-5 Years',
            stockQuantity: 18,
            vendor: 'Kuviyal',
            isCombo: true,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: '999 Combo',
            description: 'Special value combo at 999 featuring essential toys for early childhood development',
            price: 1299,
            salePrice: 999,
            saveAmount: 300,
            images: JSON.stringify(['https://example.com/combo999-1.jpg', 'https://example.com/combo999-2.jpg']),
            categoryId: 7,
            ageRange: '1-3 Years',
            stockQuantity: 32,
            vendor: 'Kuviyal',
            isCombo: true,
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Human Anatomy & Brain Puzzle Combo',
            description: 'Educational anatomy and brain puzzle set teaching body systems and brain function in a fun way',
            price: 899,
            salePrice: 749,
            saveAmount: 150,
            images: JSON.stringify(['https://example.com/anatomy-combo-1.jpg', 'https://example.com/anatomy-combo-2.jpg']),
            categoryId: 1,
            ageRange: '5-8 Years',
            stockQuantity: 25,
            vendor: 'Kuviyal',
            isCombo: true,
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            name: 'Family Entertainment Combo5',
            description: 'Family fun entertainment combo with 5 engaging toys perfect for group play and bonding',
            price: 1499,
            salePrice: 1299,
            saveAmount: 200,
            images: JSON.stringify(['https://example.com/family-combo-1.jpg', 'https://example.com/family-combo-2.jpg']),
            categoryId: 7,
            ageRange: '3-8 Years',
            stockQuantity: 20,
            vendor: 'Kuviyal',
            isCombo: true,
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Flexible Magnetic Block 25Pcs',
            description: 'Set of 25 flexible magnetic building blocks for creative construction and spatial learning',
            price: 799,
            salePrice: 649,
            saveAmount: 150,
            images: JSON.stringify(['https://example.com/magnetic-blocks-1.jpg', 'https://example.com/magnetic-blocks-2.jpg']),
            categoryId: 6,
            ageRange: '3-6 Years',
            stockQuantity: 45,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            name: 'SOCCER ROBOT',
            description: 'Interactive soccer robot with advanced movement and ball control for active play',
            price: 1299,
            salePrice: 1099,
            saveAmount: 200,
            images: JSON.stringify(['https://example.com/soccer-robot-1.jpg', 'https://example.com/soccer-robot-2.jpg']),
            categoryId: 7,
            ageRange: '5-10 Years',
            stockQuantity: 20,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-02-01').toISOString(),
        },
        {
            name: 'COLOUR CHANGING ALLOY CAR',
            description: 'Exciting alloy car that changes color with temperature - a magical toy experience',
            price: 399,
            salePrice: 299,
            saveAmount: 100,
            images: JSON.stringify(['https://example.com/alloy-car-1.jpg', 'https://example.com/alloy-car-2.jpg']),
            categoryId: 7,
            ageRange: '3-7 Years',
            stockQuantity: 60,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-02-03').toISOString(),
        },
        {
            name: 'Hot Wheels 5 Car Pack',
            description: 'Collection of 5 premium Hot Wheels cars featuring popular designs and racing styles',
            price: 599,
            salePrice: null,
            saveAmount: null,
            images: JSON.stringify(['https://example.com/hotwheels-5pack-1.jpg', 'https://example.com/hotwheels-5pack-2.jpg']),
            categoryId: 7,
            ageRange: '3-8 Years',
            stockQuantity: 35,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Hot Wheels Track Set',
            description: 'Complete Hot Wheels track set with loops, jumps and launchers for thrilling racing action',
            price: 1499,
            salePrice: 1299,
            saveAmount: 200,
            images: JSON.stringify(['https://example.com/hotwheels-track-1.jpg', 'https://example.com/hotwheels-track-2.jpg']),
            categoryId: 7,
            ageRange: '4-10 Years',
            stockQuantity: 15,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-02-07').toISOString(),
        },
        {
            name: 'Traditional Nadavandi Premium',
            description: 'Traditional Indian toy showcasing cultural heritage with authentic craftsmanship and design',
            price: 899,
            salePrice: null,
            saveAmount: null,
            images: JSON.stringify(['https://example.com/nadavandi-1.jpg', 'https://example.com/nadavandi-2.jpg']),
            categoryId: 2,
            ageRange: '2-6 Years',
            stockQuantity: 25,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-02-09').toISOString(),
        },
        {
            name: '3D Galaxy Crystal Ball Night Lamp',
            description: 'Mesmerizing 3D galaxy night lamp with crystal ball design creating magical room ambiance',
            price: 699,
            salePrice: 549,
            saveAmount: 150,
            images: JSON.stringify(['https://example.com/galaxy-lamp-1.jpg', 'https://example.com/galaxy-lamp-2.jpg']),
            categoryId: 7,
            ageRange: '5-12 Years',
            stockQuantity: 30,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-02-11').toISOString(),
        },
        {
            name: 'Friction Bulldozer Truck',
            description: 'Powerful friction-powered bulldozer truck with realistic movement and construction features',
            price: 449,
            salePrice: null,
            saveAmount: null,
            images: JSON.stringify(['https://example.com/bulldozer-1.jpg', 'https://example.com/bulldozer-2.jpg']),
            categoryId: 7,
            ageRange: '2-5 Years',
            stockQuantity: 50,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-02-13').toISOString(),
        },
        {
            name: 'Wooden Shape Sorter',
            description: 'Classic wooden shape sorter toy developing shape recognition and fine motor skills',
            price: 399,
            salePrice: null,
            saveAmount: null,
            images: JSON.stringify(['https://example.com/shape-sorter-1.jpg', 'https://example.com/shape-sorter-2.jpg']),
            categoryId: 6,
            ageRange: '1-3 Years',
            stockQuantity: 40,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-02-15').toISOString(),
        },
        {
            name: 'Musical Xylophone',
            description: 'Colorful musical xylophone introducing children to rhythm, melody and basic music concepts',
            price: 549,
            salePrice: null,
            saveAmount: null,
            images: JSON.stringify(['https://example.com/xylophone-1.jpg', 'https://example.com/xylophone-2.jpg']),
            categoryId: 2,
            ageRange: '1-4 Years',
            stockQuantity: 30,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-02-17').toISOString(),
        },
        {
            name: 'Alphabet Flash Cards',
            description: 'Complete set of alphabet flash cards with vibrant illustrations for letter recognition',
            price: 199,
            salePrice: null,
            saveAmount: null,
            images: JSON.stringify(['https://example.com/alphabet-cards-1.jpg', 'https://example.com/alphabet-cards-2.jpg']),
            categoryId: 4,
            ageRange: '2-5 Years',
            stockQuantity: 100,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-02-19').toISOString(),
        },
        {
            name: 'Animal Picture Book',
            description: 'Engaging animal picture book with realistic photos and interesting facts about wildlife',
            price: 299,
            salePrice: null,
            saveAmount: null,
            images: JSON.stringify(['https://example.com/animal-book-1.jpg', 'https://example.com/animal-book-2.jpg']),
            categoryId: 3,
            ageRange: '1-4 Years',
            stockQuantity: 75,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-02-21').toISOString(),
        },
        {
            name: 'Kids School Backpack',
            description: 'Durable and comfortable school backpack with multiple compartments and adjustable straps',
            price: 799,
            salePrice: null,
            saveAmount: null,
            images: JSON.stringify(['https://example.com/backpack-1.jpg', 'https://example.com/backpack-2.jpg']),
            categoryId: 5,
            ageRange: '3-8 Years',
            stockQuantity: 40,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-02-23').toISOString(),
        },
        {
            name: 'Stacking Rings Tower',
            description: 'Classic stacking rings tower toy helping babies learn size, color and hand-eye coordination',
            price: 349,
            salePrice: null,
            saveAmount: null,
            images: JSON.stringify(['https://example.com/stacking-rings-1.jpg', 'https://example.com/stacking-rings-2.jpg']),
            categoryId: 6,
            ageRange: '0-2 Years',
            stockQuantity: 55,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-02-25').toISOString(),
        },
        {
            name: 'Montessori Counting Beads',
            description: 'Montessori-inspired counting beads for hands-on math learning and number sense development',
            price: 599,
            salePrice: null,
            saveAmount: null,
            images: JSON.stringify(['https://example.com/counting-beads-1.jpg', 'https://example.com/counting-beads-2.jpg']),
            categoryId: 7,
            ageRange: '3-6 Years',
            stockQuantity: 35,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-02-27').toISOString(),
        },
        {
            name: 'Art & Craft Supplies Kit',
            description: 'Comprehensive art and craft supplies kit with colors, paper, glue and creative materials',
            price: 899,
            salePrice: null,
            saveAmount: null,
            images: JSON.stringify(['https://example.com/art-kit-1.jpg', 'https://example.com/art-kit-2.jpg']),
            categoryId: 8,
            ageRange: '4-10 Years',
            stockQuantity: 25,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-03-01').toISOString(),
        },
        {
            name: 'Jigsaw Puzzle 100 Pieces',
            description: '100-piece jigsaw puzzle with colorful imagery promoting problem-solving and patience',
            price: 399,
            salePrice: null,
            saveAmount: null,
            images: JSON.stringify(['https://example.com/puzzle-100-1.jpg', 'https://example.com/puzzle-100-2.jpg']),
            categoryId: 1,
            ageRange: '5-8 Years',
            stockQuantity: 45,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-03-03').toISOString(),
        },
        {
            name: 'Numbers Flash Cards',
            description: 'Numbers flash cards set teaching counting, number recognition and basic math concepts',
            price: 199,
            salePrice: null,
            saveAmount: null,
            images: JSON.stringify(['https://example.com/numbers-cards-1.jpg', 'https://example.com/numbers-cards-2.jpg']),
            categoryId: 4,
            ageRange: '2-5 Years',
            stockQuantity: 90,
            vendor: 'Kuviyal',
            isCombo: false,
            createdAt: new Date('2024-03-05').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});